### ISSUE TITLE
[BUG] Cannot read properties of undefined (reading '1')

### ISSUE THREAD

**Issue by psychedelicious** [arthurgeron/eslint-plugin-react-usememo#34]
## Minimal repro

Continuation of #26

```javascript
import { anything } from 'react'

const useMyHook = () => {
  useAnotherHook(
    ()=>{},
    []
  );
};
```

or

```js
import { anything } from 'react';

const useMyHook = (cb: () => void, deps: any[]) => {};

const MyComponent = () => {
  useMyHook(() => {}, []);
};
```

I'm getting this error where:
1. I use hooks that accept an array as any arg but the first
2. Something is imported from 'react'

### Installed packages versions
**ESLint: 8.56.0**
**Eslint-plugin-react-usememo: 2.2.1**

### Rule and its options

Which rule from the eslint-plugin-react-usememo is being used? What configuration options are set for this rule?
```
'@arthurgeron/react-usememo/require-usememo': 'error',
```

### Error log / Stack trace

```
Oops! Something went wrong! :(

ESLint: 8.56.0

TypeError: Cannot read properties of undefined (reading '1')
Occurred while linting /Users/spencer/Documents/Code/InvokeAI/invokeai/frontend/web/src/features/canvas/hooks/test.ts:4
Rule: "@arthurgeron/react-usememo/require-usememo"
    at Object.insertTextAfterRange (/Users/spencer/Documents/Code/InvokeAI/invokeai/frontend/web/node_modules/.pnpm/eslint@8.56.0/node_modules/eslint/lib/linter/rule-fixer.js:61:34)
    at Object.insertTextAfter (/Users/spencer/Documents/Code/InvokeAI/invokeai/frontend/web/node_modules/.pnpm/eslint@8.56.0/node_modules/eslint/lib/linter/rule-fixer.js:49:21)
    at addReactImports (/Users/spencer/Documents/Code/InvokeAI/invokeai/frontend/web/node_modules/.pnpm/@arthurgeron+eslint-plugin-react-usememo@2.2.1/node_modules/@arthurgeron/eslint-plugin-react-usememo/dist/index.js:2680:30)
    at fixBasedOnMessageId (/Users/spencer/Documents/Code/InvokeAI/invokeai/frontend/web/node_modules/.pnpm/@arthurgeron+eslint-plugin-react-usememo@2.2.1/node_modules/@arthurgeron/eslint-plugin-react-usememo/dist/index.js:2835:32)
    at Object.fix (/Users/spencer/Documents/Code/InvokeAI/invokeai/frontend/web/node_modules/.pnpm/@arthurgeron+eslint-plugin-react-usememo@2.2.1/node_modules/@arthurgeron/eslint-plugin-react-usememo/dist/index.js:3068:28)
    at normalizeFixes (/Users/spencer/Documents/Code/InvokeAI/invokeai/frontend/web/node_modules/.pnpm/eslint@8.56.0/node_modules/eslint/lib/linter/report-translator.js:194:28)
    at /Users/spencer/Documents/Code/InvokeAI/invokeai/frontend/web/node_modules/.pnpm/eslint@8.56.0/node_modules/eslint/lib/linter/report-translator.js:365:49
    at Object.report (/Users/spencer/Documents/Code/InvokeAI/invokeai/frontend/web/node_modules/.pnpm/eslint@8.56.0/node_modules/eslint/lib/linter/linter.js:1047:41)
    at report (/Users/spencer/Documents/Code/InvokeAI/invokeai/frontend/web/node_modules/.pnpm/@arthurgeron+eslint-plugin-react-usememo@2.2.1/node_modules/@arthurgeron/eslint-plugin-react-usememo/dist/index.js:3064:21)
    at checkForErrors (/Users/spencer/Documents/Code/InvokeAI/invokeai/frontend/web/node_modules/.pnpm/@arthurgeron+eslint-plugin-react-usememo@2.2.1/node_modules/@arthurgeron/eslint-plugin-react-usememo/dist/index.js:2643:13)
```

**Comment by arthurgeron** [comment]
Thank you for providing all the info needed for a fix @psychedelicious !

**Comment by psychedelicious** [comment]
@arthurgeron No worries. Thanks for the super quick fix!
